"""Initial migration

Revision ID: ac876de767fc
Revises: 
Create Date: 2026-07-14 17:11:42.286250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac876de767fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='project_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('project_contexts',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('user_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('business_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('authentication_type', sa.String(length=100), nullable=True),
    sa.Column('supported_platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('additional_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_contexts_project_id'), 'project_contexts', ['project_id'], unique=True)
    op.create_table('requirements',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('business_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requirement_type', sa.Enum('USER_STORY', 'FEATURE', 'API', 'BUSINESS_REQUIREMENT', 'OTHER', name='requirement_type'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='requirement_priority'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'ANALYZED', 'ARCHIVED', name='requirement_status'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_project_id'), 'requirements', ['project_id'], unique=False)
    op.create_table('ai_generations',
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('generation_type', sa.Enum('REQUIREMENT_REVIEW', 'TEST_GENERATION', 'COVERAGE_ANALYSIS', 'AUTOMATION_RECOMMENDATION', name='generation_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='generation_status'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generations_requirement_id'), 'ai_generations', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_ai_generations_status'), 'ai_generations', ['status'], unique=False)
    op.create_table('coverage_analyses',
    sa.Column('generation_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('coverage_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('covered_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['ai_generations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coverage_analyses_generation_id'), 'coverage_analyses', ['generation_id'], unique=True)
    op.create_index(op.f('ix_coverage_analyses_requirement_id'), 'coverage_analyses', ['requirement_id'], unique=False)
    op.create_table('generated_artifacts',
    sa.Column('generation_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.Enum('TEST_CASES', 'CHECKLIST', 'NEGATIVE_SCENARIOS', 'EDGE_CASES', 'REQUIREMENT_REVIEW', 'AUTOMATION_RECOMMENDATIONS', name='artifact_type'), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['ai_generations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_artifacts_artifact_type'), 'generated_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_generated_artifacts_generation_id'), 'generated_artifacts', ['generation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_artifacts_generation_id'), table_name='generated_artifacts')
    op.drop_index(op.f('ix_generated_artifacts_artifact_type'), table_name='generated_artifacts')
    op.drop_table('generated_artifacts')
    op.drop_index(op.f('ix_coverage_analyses_requirement_id'), table_name='coverage_analyses')
    op.drop_index(op.f('ix_coverage_analyses_generation_id'), table_name='coverage_analyses')
    op.drop_table('coverage_analyses')
    op.drop_index(op.f('ix_ai_generations_status'), table_name='ai_generations')
    op.drop_index(op.f('ix_ai_generations_requirement_id'), table_name='ai_generations')
    op.drop_table('ai_generations')
    op.drop_index(op.f('ix_requirements_project_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_project_contexts_project_id'), table_name='project_contexts')
    op.drop_table('project_contexts')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
